variables:
  GROUP_ID: be/lampiris/demo
  PROJECT: docker-swarm
  VERSION: 1.0.0

stages:
  - deploy

.swarm-deploy: &swarm-deploy
  stage: deploy
  variables:
    DOCKER_HOST: tcp://$ACTIVATION_SWARM_HOST_1
    SERVICE_NAME: default-app
  image: docker:latest
  script:
    - docker -H tcp://10.20.130.11:2375 ps
  environment:
    name: master
    url: http://${CI_BUILD_REF_NAME}.lampiris.be
  when: manual
  only:
    - master
    - /^feature.*$/

swarm-deploy-mono-voteapp:
  <<: *swarm-deploy
  variables:
    DOCKER_HOST: tcp://$ACTIVATION_SWARM_HOST_1
    SERVICE_NAME: vote-app
  script:
    - docker -H tcp://10.20.130.11:2375 ps
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack deploy --compose-file=./swarm/vote-app/docker-compose-mono.yml ${CI_ENVIRONMENT_SLUG}-${SERVICE_NAME}

swarm-deploy-cluster-voteapp:
  <<: *swarm-deploy
  variables:
    DOCKER_HOST: tcp://$ACTIVATION_SWARM_HOST_1
    SERVICE_NAME: vote-app
  script:
    - docker -H tcp://10.20.130.11:2375 ps
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack deploy --compose-file=./swarm/vote-app/docker-compose-cluster.yml ${CI_ENVIRONMENT_SLUG}-${SERVICE_NAME}

swarm-undeploy-voteapp:
  <<: *swarm-deploy
  variables:
    DOCKER_HOST: tcp://$ACTIVATION_SWARM_HOST_1
    SERVICE_NAME: vote-app
  script:
    - docker -H tcp://10.20.130.11:2375 ps
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack rm ${CI_ENVIRONMENT_SLUG}-${SERVICE_NAME}

