variables:
  GROUP_ID: be/lampiris/demo
  PROJECT: docker-swarm
  VERSION: 1.0.0

stages:
  - deploy

swarm-deploy:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://$ACTIVATION_SWARM_HOST_1
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: ./swarm
    SERVICE_NAME: vote-app
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack deploy --compose-file=./swarm/vote-app/docker-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${SERVICE_NAME}
#    - docker stack deploy --with-registry-auth --compose-file=docker-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${SERVICE_NAME}
  environment:
    name: master
    url: http://${CI_BUILD_REF_NAME}.lampiris.be
  when: manual
  only:
    - master