version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  grafana:
    image: grafana/grafana
    networks:
      - grafana_webgateway
      - web
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    env_file:
      - 'grafana.conf'
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.backend=grafana"
        - "traefik.frontend.rule=Host:grafana.activation.lampiris.io"
      placement:
        constraints: [node.role == manager]

  influxdb:
    image: influxdb:latest
    networks:
      - grafana_webgateway
    env_file:
      - 'influxdb.conf'

  telegraf:
    image: telegraf:latest
    networks:
      - grafana_webgateway
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro


networks:
  grafana_webgateway:
  web:
    external:
      name: traefik_webgateway
